# -*- coding: utf-8 -*-
"""CSE544_A4_Q6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oE6olXM_Hv3rtdfvQZMdtcqoM2UUu2fp
"""

import numpy as np

X = np.loadtxt('q6_X.dat')
Y = np.loadtxt('q6_Y.dat')

print ("Question 6b")
mu_x_hat = np.mean(X)
mu_y_hat = np.mean(Y)
delta_hat = mu_x_hat - mu_y_hat
var_x = np.sum(np.square(X-mu_x_hat))/len(X)
var_y = np.sum(np.square(Y-mu_y_hat))/len(Y)
se_hat = np.sqrt((var_x + var_y)/len(X))
W = np.absolute(delta_hat/se_hat)
print("|W| = ", W)
if W > 1.96:
  print("Rejecting the null hypothesis that states the population means of X and Y are same")
else:
  print("Accepting the null hypothesis that states the population means of X and Y are same")

print ("Question 6c")

D_bar = mu_x_hat - mu_y_hat
sd_D = np.sqrt(np.sum(np.square(X-Y-mu_x_hat+mu_y_hat))/len(X))
T = np.absolute(D_bar * np.sqrt(len(X))/sd_D)
print("|T| = ", T)
if T > 1.962:
  print("Rejecting the null hypothesis that states the population means of X and Y are same")
else:
  print("Accepting the null hypothesis that states the population means of X and Y are same")

