# -*- coding: utf-8 -*-
"""cse544_A6_q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19gy3fROH1O6s7qRVQhbRBEXwVgXeBrHX
"""

import numpy as np

data = np.loadtxt("q4.dat", delimiter="\t")

batch = int(len(data)/4)

X1 = data[:batch, 0]
Y1 = data[:batch, 1]

X2 = data[batch:2*batch, 0]
Y2 = data[batch:2*batch, 1]

X3 = data[2*batch:3*batch, 0]
Y3 = data[2*batch:3*batch, 1]

X4 = data[3*batch:, 0]
Y4 = data[3*batch:, 1]

#definition: b1_hat = (sum(X_i*Y_i) - n*Xbar*Ybar)/(sum(Xi*Xi) - n*Xbar*Xbar)
#definition: b0_hat = Ybar - b1_hat*Xbar
#definition: Y_i_hat = b0_hat + b1_hat*X_i

def calculate_b1hat(X,Y):
    b1_hat = (np.sum(X*Y) - (np.mean(X)*np.mean(Y)*len(X)))/(np.sum(X*X) - (len(X)*np.mean(X)*np.mean(X)))
    return b1_hat

def calculate_b0hat(X,Y,b1_hat):
    b0_hat = np.mean(Y) - (b1_hat*np.mean(X))
    return b0_hat
  
def calculate_Yhat(b0_hat, b1_hat, X):
  Y_hat = b0_hat + (b1_hat*X)
  return Y_hat

b11_hat = calculate_b1hat(X1, Y1)
b01_hat = calculate_b0hat(X1, Y1, b11_hat)
Y1_hat = calculate_Yhat(b01_hat, b11_hat, X1)

b12_hat = calculate_b1hat(X2, Y2)
b02_hat = calculate_b0hat(X2, Y2, b12_hat)
Y2_hat = calculate_Yhat(b02_hat, b12_hat, X2)

b13_hat = calculate_b1hat(X3, Y3)
b03_hat = calculate_b0hat(X3, Y3, b13_hat)
Y3_hat = calculate_Yhat(b03_hat, b13_hat, X3)

b14_hat = calculate_b1hat(X4, Y4)
b04_hat = calculate_b0hat(X4, Y4, b14_hat)
Y4_hat = calculate_Yhat(b04_hat, b14_hat, X4)

import matplotlib.pyplot as plt

plt.plot(X1, Y1, 'r', label='Original data') 
plt.plot(X1, Y1_hat, 'g', label='Fitted line') 
plt.title("Quarter 1")
plt.legend() 
plt.show()

plt.plot(X2, Y2, 'r', label='Original data') 
plt.plot(X2, Y2_hat, 'g', label='Fitted line') 
plt.title("Quarter 2")
plt.legend() 
plt.show()

plt.plot(X3, Y3, 'r', label='Original data') 
plt.plot(X3, Y3_hat, 'g', label='Fitted line') 
plt.title("Quarter 3")
plt.legend() 
plt.show()

plt.plot(X4, Y4, 'r', label='Original data') 
plt.plot(X4, Y4_hat, 'g', label='Fitted line') 
plt.title("Quarter 4")
plt.legend() 
plt.show()

def calculate_sse(Y, Y_hat):
  return np.sum(np.square(Y-Y_hat))

sse1 = calculate_sse(Y1, Y1_hat)
sse2 = calculate_sse(Y2, Y2_hat)
sse3 = calculate_sse(Y3, Y3_hat)
sse4 = calculate_sse(Y4, Y4_hat)

sse = [sse1, sse2, sse3, sse4]

import pandas as pd

sse_df = pd.DataFrame(sse, columns=["SSE"])
sse_df.index = ["Quarter 1", "Quarter 2", "Quarter 3", "Quarter 4"]
sse_df

sse

